"""empty message

Revision ID: 160b3a70b949
Revises: 946329352092
Create Date: 2022-11-15 14:03:16.556947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160b3a70b949'
down_revision = '946329352092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'category', 'user', ['user'], ['id'])
    op.drop_column('category', 'creater_id')
    op.create_foreign_key(None, 'recipe', 'category', ['category'], ['id'])
    op.drop_column('recipe', 'creater_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('creater_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.add_column('category', sa.Column('creater_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    # ### end Alembic commands ###
