"""empty message

Revision ID: 1a95164f4cf2
Revises: f1e8846d26b4
Create Date: 2022-11-23 13:38:19.750258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a95164f4cf2'
down_revision = 'f1e8846d26b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recipe', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='unique')
    # ### end Alembic commands ###
