"""empty message

Revision ID: 60802e648fc6
Revises: a80aede6cf36
Create Date: 2022-11-09 21:20:44.793725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60802e648fc6'
down_revision = 'a80aede6cf36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'poster_id')
    op.add_column('recipe', sa.Column('creater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'user', ['creater_id'], ['id'])
    op.create_foreign_key(None, 'recipe', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'creater_id')
    op.add_column('category', sa.Column('poster_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
