"""empty message

Revision ID: 7f2f3e20efe0
Revises: 8566b2cb72d1
Create Date: 2022-11-09 22:16:31.101762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2f3e20efe0'
down_revision = '8566b2cb72d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('creater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['creater_id'], ['id'])
    op.create_foreign_key(None, 'recipe', 'category', ['category'], ['id'])
    op.create_foreign_key(None, 'recipe', 'user', ['creater_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'creater_id')
    # ### end Alembic commands ###
