"""empty message

Revision ID: 8566b2cb72d1
Revises: 60802e648fc6
Create Date: 2022-11-09 21:58:59.176169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8566b2cb72d1'
down_revision = '60802e648fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recipe', 'category', ['category'], ['id'])
    op.drop_column('recipe', 'creater_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('creater_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    # ### end Alembic commands ###
