"""empty message

Revision ID: 8dff3da02e6a
Revises: c188f303c36c
Create Date: 2022-11-17 11:26:05.967789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dff3da02e6a'
down_revision = 'c188f303c36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.drop_column('category', 'user')
    op.drop_column('category', 'creater_id')
    op.create_foreign_key(None, 'recipe', 'category', ['category'], ['id'])
    op.drop_column('recipe', 'creater_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('creater_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.add_column('category', sa.Column('creater_id', sa.INTEGER(), nullable=True))
    op.add_column('category', sa.Column('user', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    # ### end Alembic commands ###
