"""empty message

Revision ID: 946329352092
Revises: 6aa8624bf20f
Create Date: 2022-11-15 12:11:09.649035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946329352092'
down_revision = '6aa8624bf20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'category', 'user', ['user'], ['id'])
    op.drop_column('category', 'creater_id')
    op.add_column('recipe', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'category', ['category'], ['id'])
    op.create_foreign_key(None, 'recipe', 'user', ['user'], ['id'])
    op.drop_column('recipe', 'creater_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('creater_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'user')
    op.add_column('category', sa.Column('creater_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    # ### end Alembic commands ###
