"""empty message

Revision ID: a80aede6cf36
Revises: 
Create Date: 2022-11-09 18:33:09.190716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80aede6cf36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['poster_id'], ['id'])
    op.add_column('recipe', sa.Column('creater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'user', ['creater_id'], ['id'])
    op.create_foreign_key(None, 'recipe', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'creater_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'poster_id')
    # ### end Alembic commands ###
