"""empty message

Revision ID: c188f303c36c
Revises: 160b3a70b949
Create Date: 2022-11-16 10:53:55.780185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c188f303c36c'
down_revision = '160b3a70b949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.drop_column('category', 'user')
    op.drop_column('category', 'creater_id')
    op.add_column('recipe', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'recipe', 'category', ['category'], ['id'])
    op.drop_column('recipe', 'creater_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('creater_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'user_id')
    op.add_column('category', sa.Column('creater_id', sa.INTEGER(), nullable=True))
    op.add_column('category', sa.Column('user', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###
