"""empty message

Revision ID: e3e88b94264f
Revises: 1a95164f4cf2
Create Date: 2022-11-23 13:39:13.576522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e88b94264f'
down_revision = '1a95164f4cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recipe', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='unique')
    # ### end Alembic commands ###
